blank_issues_enabled: true
contact_links:
  - name: Forestry Discord Server
    url: https://discord.gg/yHyHwGQ8ux
    about: Please use our Discord for questions or help. Issues should be used for bug reports, feature requests or similar.
