name: Publish

on:
  release:
    types:
      - published

permissions:
  contents: write

jobs:
  publish:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: Generate data
        run: ./gradlew runData
        env:
          FORESTRY_VERSION: ${{ github.event.release.tag_name }}
      - name: Build
        run: ./gradlew build
        env:
          FORESTRY_VERSION: ${{ github.event.release.tag_name }}
      - name: Upload Release Artifact
        uses: softprops/action-gh-release@v1
        with:
          files: build/libs/forestry-${{ github.event.release.tag_name }}.jar
          tag_name: ${{ github.event.release.tag_name }}
      - name: Upload to CurseForge
        run: ./gradlew curseforge
        env:
          FORESTRY_VERSION: ${{ github.event.release.tag_name }}
          CURSEFORGE: ${{ secrets.CURSEFORGE }}
      - name: Upload to Modrinth
        run: ./gradlew modrinth
        env:
          FORESTRY_VERSION: ${{ github.event.release.tag_name }}
          MODRINTH: ${{ secrets.MODRINTH }}
